volumes:
  dev-db-volume: {}
services:
  dev-pg:
    container_name: dbpg
    hostname: hostname
    image: bitnami/postgresql:17.2.0
    environment:
      POSTGRESQL_DATABASE: task-management
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: admin
    volumes:
      - dev-db-volume:/bitnami/postgresql
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eoeqs"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:

    container_name: back_app
    hostname: bbb
    depends_on:
      dev-pg:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '8080:8080'

